### ISSUE TITLE
Rotation

### ISSUE THREAD

**Issue by mattncsu** [squix78/minigrafx#2]
Is it possible to draw some text in a different rotation from the rest of the sketch? I tried
`gfx.setRotation(0);`
`gfx.drawString(10, 10, "Hello World");`
`gfx.setRotation(1);`
`gfx.drawString(20, 20, "Hello World");`
`gfx.commit;`
but rotating between drawString calls corrupted the buffer.

I'm using the Waveshare 2.9 display on a Huzzah Feather.

**Comment by squix78** [comment]
I have rotated text on my backlog but could not implement it yet. Your rotation trick probably doesn't work because it only takes real effect once the buffer is written to the display.
I would either implement it with an additional setTextRotationMethod plus adapting the drawString method or by adding a overloaded drawString method with additional rotation parameter...
Let me know if you are interested in contributing this feature by pull request and we'll discuss the design...

**Comment by mattncsu** [comment]
I'm can sure try to contribute although my abilities are mostly limited to hacking together code from different places.  I'd start with [this](https://github.com/loboris/ESP32_ePaper_example/blob/master/components/epaper/EPD.c) library written for the ESP32.  I did write an invert colors function for your library that I can try and figure out how to get it into MiniGrafx.cpp (It is just a function in EPD_WaveShare_2_9.ino right now) and make that my first official pull request.

**Comment by mattncsu** [comment]
I have some basic functionality (https://github.com/squix78/minigrafx/pull/3/files) that works for some limited angles but usually ends up off screen because the text is spinning about some odd point.  Most of the functionality is in setPixel90().  Any suggestions?
